name: Linting

on:
  push:
    branches: [ main ]  # On pushes to main
  pull_request:
    branches: [ main ]  # On pull to main

jobs:
  lint:
    runs-on: ubuntu-latest  # Use most recent Ubuntu

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch full history to avoid shallow clone issues

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Check Python Version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black  # Install Flake8 and Black

      - name: Run flake8
        run: |
          flake8 . #--max-line-length=88  # Adjust max-line-length to match Black's default of 88

      - name: Auto-fix with Black
        if: failure()
        run: |
          black .
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Apply Black formatting fixes" || echo "No changes to commit"

      # Create new branch
      - name: Create a new branch
        if: failure()
        run: |
          git checkout -b auto-lint-fixes
          git add .
          git commit -m "Apply Black formatting fixes" || echo "No changes to commit"

      # new branch push
      - name: Push changes to a new branch
        if: failure()
        run: git push origin auto-lint-fixes --force
          
      # Pull request on new branch
      - name: Create Pull Request
        if: failure()
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: auto-lint-fixes
          base: main
          title: "Auto-fix: Black formatting applied"
          body: "This pull request contains auto-formatting fixes made by Black."
