name: Linting

on:
  push:
    branches: [ main ]  # On pushes to main
  pull_request:
    branches: [ main ]  # On pull to main

jobs:
  lint:
    runs-on: ubuntu-latest  # Use most recent Ubuntu

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Check Python Version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black  # Install Flake8 and Black

      - name: Run flake8
        run: |
          flake8 . #--max-line-length=88  # Adjust max-line-length to match Black's default of 88

      - name: Auto-fix with Black
        if: failure()
        run: |
          black .
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Apply Black formatting fixes" || echo "No changes to commit"
      # Pull repo to prevent version error
      - name: Pull latest changes
        if: failure()
        run: |
          git pull origin main --rebase || echo "No changes to pull"

      # Push Change
      - name: Push changes
        if: failure()
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
